sudo: required

env:
  - query=1
  - query=2
  - query=3
  - query=4
  - query=5
  - query=6
  - query=7
  - query=8
  - query=9
  - query=10
  - query=11
  - query=12
  - query=13
  - query=14
  - query=15
  - query=16
  - query=17
  - query=18
  - query=19
  - query=20
  - query=21
  - query=22

services:
  - docker

install:
  - shopt -s expand_aliases

script:
  - docker-compose -f docker/docker-compose.yml up -d namenode hive-metastore-postgresql datanode hive-metastore hive-server && docker exec hive-server bash -c "git clone https://github.com/dharmeshkakadia/tpch-datagen-as-hive-query/ && cd tpch-datagen-as-hive-query && hive -i settings.hql -f TPCHDataGen.hql -hiveconf SCALE=2 -hiveconf PARTS=2 -hiveconf LOCATION=/HiveTPCH/ -hiveconf TPCHBIN=resources && hive -i settings.hql -f ddl/createAllExternalTables.hql -hiveconf LOCATION=/HiveTPCH/ -hiveconf DBNAME=tpch" 
  - docker exec hive-server bash -c "hive -database tpch -i tpch-datagen-as-hive-query/settings.hql -f tpch-datagen-as-hive-query/queries/tpch_query${query}.hql"